title: C++ - od podstaw do matury rozszerzonej
description: Kurs programowania w C++ przygotowujący od podstaw do matury rozszerzonej z informatyki
baseurl: "/cpp-matura-2026"
theme: jekyll-theme-slate
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default
